#!/usr/bin/env python3
"""
Usage: update_md_pics.py

Updates the autogenerated Markdown snippets for all *.md files in the current directory and subdirectories.

It scans each Markdown file for the markers <!-- $Begin-Autogenerated$ <template> ... --> and <!-- $End-Autogenerated$ -->,
and replaces the content between these markers. The content depends on the template specified in the $Begin-Autogenerated$ 
marker, and any arguments that may follow it. The templates are defined below.

The output is idempotent, meaning that running the script multiple times will yield the same result as running it once,
as long as the underlying data (e.g., pics.yaml) does not change.

"""

import os
import re
import yaml


with open('pics.yaml', 'r') as f:
    pics_catalog = yaml.safe_load(f)


def md_img(pics, url, caption):
    thumb_url_gen = pics.get('thumb_url_gen', {})
    thumb_url = re.sub(thumb_url_gen['match'], thumb_url_gen['replace'], url)
    return f'[![{caption}]({thumb_url})]({url})'


def generate_slot_pics_snippets(pics, card, slot):
    """
    Generates a list of Markdown snippets for the pictures of a card in a specific slot.
    The snippets include the image thumbnail and the caption (as alt text and printed below the image),
    and links to the full-size image.

    Args:
        pics (dict): The loaded pics catalog from YAML.
        card (str): The card name.
        slot (str): The slot number as a string.

    Returns:
        list: A list of Markdown snippet strings.
    """
    snippets = []

    for pic in pics['pics']:
        if pic.get('card') != card:
            continue

        slots = [str(s) for s in pic.get('slots', [])]
        if slot not in slots:
            continue

        caption = pic['caption']
        url = pic['url']
        md_snippet = f'{caption}:\n\n{md_img(pics, url, caption)}\n\n'
        snippets.append(md_snippet)

    return snippets


def generate_featured_pic_snippet(pics, card):
    """
    Generates a Markdown snippet for the featured picture of a card, given the card name.
    The featured picture is the one with the "featured: true" flag in the referenced pics catalog.
    The snippet includes the image thumbnail and the caption, and links to the full-size image.
    """

    for pic in pics['pics']:
        if pic.get('card') == card and pic.get('featured'):
            caption = pic['caption']
            url = pic['url']
            md_snippet = f'{md_img(pics, url, caption)}\n\n{caption}\n\n\n'
            return md_snippet
        
    return f'<!-- No featured picture found for card {card} -->\n'
        

def template_gen_card_featured_pic_md(card_id):
    snippet = generate_featured_pic_snippet(pics_catalog, card_id)
    return snippet

def template_gen_slot_pics_md(card_id, slot_id):
    snippets = generate_slot_pics_snippets(pics_catalog, card_id, slot_id)
    return '\n'.join(snippets) + '\n'


def template_gen_desk_pics_md():
    def make_desk_pic_snippet(pic):
        caption = pic['caption']
        url = pic['url']
        return f'{caption}:\n\n{md_img(pics_catalog, url, caption)}\n\n'
    
    return '\n'.join(make_desk_pic_snippet(pic) \
                     for pic in pics_catalog['pics'] \
                        if pic.get('desk')) + '\n'


templates = {
    'FeaturedPic': template_gen_card_featured_pic_md,
    'SlotGallery': template_gen_slot_pics_md,
    'DeskGallery': template_gen_desk_pics_md,
}

def update_md_pics(md_file):
    with open(md_file, 'r') as f:
        content = f.read()

    pattern = r'<!-- \$Begin-Autogenerated\$ (.+?) -->\n(.*?)<!-- \$End-Autogenerated\$ -->'
    matches = re.finditer(pattern, content, re.DOTALL)

    replacements = []
    for match in matches:
        snippet_params = match.group(1).strip()
        template_id = snippet_params.split()[0]
        args = snippet_params.split()[1:]
        replacements.append((match.start(), match.end(), template_id, args))

    # Generate all snippets in reverse order to avoid messing up indices
    for start, end, template_id, args in reversed(replacements):
        if template_id in templates:
            print(f'Updating {template_id} snippet with args {args} in {md_file}...')
            new_snippet = templates[template_id](*args)
        else:
            print(f'Unknown template: {template_id} in {md_file}')
            continue

        content = content[:start] + f'<!-- $Begin-Autogenerated$ {template_id} {" ".join(args)} -->\n{new_snippet}<!-- $End-Autogenerated$ -->' + content[end:]

    with open(md_file, 'w') as f:
        f.write(content)


if __name__ == '__main__':
    for root, _, files in os.walk('.'):
        for file in files:
            if file.endswith('.md'):
                md_file = os.path.join(root, file)
                print(f'Updating {md_file}...')
                update_md_pics(md_file)