#!/usr/bin/env python3
"""
Usage: update_md_pics.py

Updates the autogenerated Markdown snippets for all *.md files in the current directory and subdirectories.

It scans each Markdown file for the markers <!-- $Begin-Autogenerated$ <template> ... --> and <!-- $End-Autogenerated$ -->,
and replaces the content between these markers. The content depends on the template specified in the $Begin-Autogenerated$ 
marker, and any arguments that may follow it. The templates are defined below.

The output is idempotent, meaning that running the script multiple times will yield the same result as running it once,
as long as the underlying data (e.g., pics.yaml) does not change.

"""

import os
import re
import subprocess
import gen_slot_pics_md
import yaml


with open('../pics.yaml', 'r') as f:
    pics_catalog = yaml.safe_load(f)


def template_gen_card_featured_pic_md(card_id):
    return subprocess.check_output(['python3', 'gen_card_featured_pic_md.py', '../pics.yaml', card_id]).decode('utf-8')

def template_gen_slot_pics_md(card_id, slot_id):
    snippets = gen_slot_pics_md.generate_snippets(pics_catalog, card_id, slot_id)
    return '\n'.join(snippets) + '\n'

templates = {
    'FeaturedPic': template_gen_card_featured_pic_md,
    'SlotGallery': template_gen_slot_pics_md
}

def update_md_pics(md_file):
    with open(md_file, 'r') as f:
        content = f.read()

    pattern = r'<!-- \$Begin-Autogenerated\$ (.+?) -->\n(.*?)<!-- \$End-Autogenerated\$ -->'
    matches = re.finditer(pattern, content, re.DOTALL)

    replacements = []
    for match in matches:
        snippet_params = match.group(1).strip()
        template_id = snippet_params.split()[0]
        args = snippet_params.split()[1:]
        replacements.append((match.start(), match.end(), template_id, args))

    # Generate all snippets in reverse order to avoid messing up indices
    for start, end, template_id, args in reversed(replacements):
        if template_id in templates:
            print(f'Updating {template_id} snippet with args {args} in {md_file}...')
            new_snippet = templates[template_id](*args)
        else:
            print(f'Unknown template: {template_id} in {md_file}')
            continue

        content = content[:start] + f'<!-- $Begin-Autogenerated$ {template_id} {" ".join(args)} -->\n{new_snippet}<!-- $End-Autogenerated$ -->' + content[end:]

    with open(md_file, 'w') as f:
        f.write(content)


if __name__ == '__main__':
    for root, _, files in os.walk('.'):
        for file in files:
            if file.endswith('.md'):
                md_file = os.path.join(root, file)
                print(f'Updating {md_file}...')
                update_md_pics(md_file)